### ISSUE TITLE
kcp ReplicaSet is rejected in OpenShift

### ISSUE THREAD

**Issue by MikeSpreitzer** [kcp-dev/helm-charts#52]
I tried using the Helm chart to create a Helm "release" in an OpenShift cluster, and the ReplicaSet for the kcp server is unacceptable to OpenShift.

I put the following in my values YAML:

```yaml
externalHostname: "some-long.stuff.containers.appdomain.cloud"
kcp:
  volumeClassName: "default"
kcpFrontProxy:
  openshiftRoute:
    enabled: true
```

I found that the ReplicaSet for kcp never got any Pod object created.  A `kubectl describe` of that ReplicaSet included the following Event, which explains the problem (line breaks added for readability).

```
  Warning  FailedCreate  42s (x17 over 6m10s)  replicaset-controller  
Error creating: pods "kcp-75d5778b7d-" is forbidden: 
unable to validate against any security context constraint: [
provider "anyuid": Forbidden: not usable by user or serviceaccount,
provider restricted-v2: .spec.securityContext.fsGroup: Invalid value: []int64{65532}: 65532 is not an allowed group,
provider "restricted": Forbidden: not usable by user or serviceaccount,
provider "ibm-restricted-scc": Forbidden: not usable by user or serviceaccount,
provider "nonroot-v2": Forbidden: not usable by user or serviceaccount,
provider "nonroot": Forbidden: not usable by user or serviceaccount,
provider "ibm-anyuid-scc": Forbidden: not usable by user or serviceaccount,
provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount,
provider "ibm-anyuid-hostpath-scc": Forbidden: not usable by user or serviceaccount,
provider "hostnetwork-v2": Forbidden: not usable by user or serviceaccount,
provider "hostnetwork": Forbidden: not usable by user or serviceaccount,
provider "hostaccess": Forbidden: not usable by user or serviceaccount,
provider "ibm-anyuid-hostaccess-scc": Forbidden: not usable by user or serviceaccount,
provider "node-exporter": Forbidden: not usable by user or serviceaccount,
provider "ibm-privileged-scc": Forbidden: not usable by user or serviceaccount,
provider "privileged": Forbidden: not usable by user or serviceaccount]
```

**Comment by MikeSpreitzer** [comment]
I tried a few work-arounds, none with full success, described in Slack starting at https://kubernetes.slack.com/archives/C021U8WSAFK/p1691118703785549

**Comment by MikeSpreitzer** [comment]
@pdettori said that this is fixed in `main`.  I must admit that I do not remember whether I tested `main` or the latest release.

**Comment by pdettori** [comment]
@embik thanks, would it be possible to publish a new release for the helm chart (e.g. 0.2.6) since the latest release (0.2.5) does not include the change and so setting security context is still not possible following the instructions for usage in https://github.com/kcp-dev/helm-charts#usage

**Comment by embik** [comment]
@pdettori I believe the securityContext changes mentioned in this specific issue never made it into a release (0.2.5 is from February and the commit that broke OpenShift deployment as far as I understood must have been https://github.com/kcp-dev/helm-charts/commit/be75345f70e6819991145801fd8e4ac44d4c1ee4). Or is this a separate concern just related to being able to set the securityContext at all?

In any case, I think we are planning to release 0.3.0 somewhat soonish since there are one or two breaking changes either merged already or planned. At that point the chart should be much more flexible.

**Comment by embik** [comment]
@pdettori FYI, chart version 0.3.0 has been released. Maybe someone can check if this issue is still present / cannot be fixed by overriding the securityContext in `values.yaml`.
